name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ${{ matrix.os }}
    resources:
      cores: 8
      memory: 32GB
    permissions:
      packages: write
      contents: read
      attestations: write
    strategy:
      matrix:
        os: [ubuntu-22.04]
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - name: Set up QEMU (only for non-native architectures)
        if: ${{ matrix.platform != 'linux/amd64' }}
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ambarltd
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ambarltd/emulator

      - name: Build and push Docker image for ${{ matrix.platform }}
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./build/
          file: ./build/Dockerfile
          push: true
          platforms: ${{ matrix.platform }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
